name: wow-private-server-website
volumes:
  caddy_data:
  caddy_config:
networks:
  default:
services:
  app:
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  app-dev:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/app:ro
      - caddy_data:/data
      - caddy_config:/config
  mariadb:
    image: mariadb:11.8
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - default
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
